### ISSUE TITLE
Add support fo excalidraw embeds

### ISSUE THREAD

**Issue by jsjoeio** [jsjoeio/joeprevite.com#124]
## Summary

https://twitter.com/jsjoeio/status/1258115302199406592?s=21

### Basic example

Add exacalidraw link to markdown

at build time, turns into svg

### Motivation

Why are we doing this? What use cases does it support? What is the expected outcome?

**Comment by jsjoeio** [comment]
more examples and details: https://github.com/trevorblades/excalidraw-embed

make sure to thank and add to contributors:
- @j-f1 
- @trevorblades

**Comment by trevorblades** [comment]
Is it cool if I add your site to an "In the wild" section in the readme after you've implemented it?

**Comment by jsjoeio** [comment]
> Is it cool if I add your site to an "In the wild" section in the readme after you've implemented it?

100%! 🥳

**Comment by jsjoeio** [comment]
@all-contributors please add @j-f1 and @trevorblades for code

**Comment by jsjoeio** [comment]
@all-contributors please add @trevorblades for code
