### ISSUE TITLE
Migrate to TypeScript

### ISSUE THREAD

**Issue by jsjoeio** [jsjoeio/joeprevite.com#16]
## Summary

Migrate entire codebase to TypeScript

### Basic example

N/A

### Motivation

- type safety
- catch errors before they happen at runtime
- good practice
- better documentation/autocomplete
- fun 😄

**Comment by v1rtl** [comment]
> * fun :smile: 

I'd argue here :laughing:

**Comment by jsjoeio** [comment]
lol you're probably right but this is my way of tricking myself into "thinking" it's fun 😂
