### ISSUE TITLE
Set Up RSS Feed 

### ISSUE THREAD

**Issue by jsjoeio** [jsjoeio/joeprevite.com#49]
## Summary

set up an RSS feed for posts

### Basic example

a simple RSS feed

### Motivation

@chriscoyier [might read my blog](https://twitter.com/chriscoyier/status/1214606808125341696?s=20) if it has an RSS feed.

**Comment by jsjoeio** [comment]
@tatianamac asked about one! Another sign that you (Joe) should get on this!

**Comment by tatianamac** [comment]
(I love the idea of contributing to a colleague/friend's blog as OSS contribution 😂)

**Comment by jsjoeio** [comment]
https://twitter.com/alexott_en/status/1291354085568937985?s=20

**Comment by alexott** [comment]
I want to add blog to planet clojure: https://github.com/ghoseb/planet.clojure

**Comment by jsjoeio** [comment]
It will also allow me to show my latest posts in my GitHub README profile!

https://github.com/pawelgrzybek/pawelgrzybek

**Comment by alexott** [comment]
added to Planet...
