### ISSUE TITLE
Add animation to Logo

### ISSUE THREAD

**Issue by jsjoeio** [jsjoeio/joeprevite.com#52]
## Summary

Make the JP fade in on load.
Make it spin on hover. 

### Basic example

[Like this](https://codesandbox.io/s/xlrx1?module=%2Fsrc%2FExample.tsx)

### Motivation

Add some flava flav to the site 🕺

**Comment by willjohnsonio** [comment]
Do you want it to fade in on load?

**Comment by jsjoeio** [comment]
@wjohnson85 Yeah, I think that would be sick! I'll update the summary
